Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "public_network"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y nginx

    # Change Nginx port to 82
    sudo sed -i 's/listen 80 default_server/listen 82 default_server/g' /etc/nginx/sites-available/default

    systemctl restart nginx
  SHELL
end
