# Use Python 3.9 slim image as the base
FROM python:3.9-slim

# Set working directory in the container
WORKDIR /app

# Copy requirements.txt
COPY requirements.txt .

# Copy your application code
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Expose port 8000
EXPOSE 8000

# Define Gunicorn command to run the API
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "rest:app"]
