Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600

  # Jenkins Master VM
  config.vm.define "jenkins-master" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end

    master.vm.provision "shell", inline: <<-SHELL
      # Update package repositories and install Java 11
      sudo apt update
      sudo apt install -y openjdk-11-jdk

      # Download Jenkins WAR file
      wget https://get.jenkins.io/war-stable/latest/jenkins.war -O /opt/jenkins.war

      # Start Jenkins with Java 11
      java -jar /opt/jenkins.war &
    SHELL
  end

  # Jenkins Worker VM
  config.vm.define "jenkins-worker" do |worker|
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.network "private_network", ip: "192.168.56.11"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end

    worker.vm.provision "shell", inline: <<-SHELL
      # Update package repositories and install Java 11
      sudo apt update
      sudo apt install -y openjdk-11-jdk
    SHELL
  end
end
