Vagrant.configure("2") do |config|

  # Global Environment Variables (Available to both VMs)
  config.vm.provision "shell", inline: "export APP_USER=app_user"
  config.vm.provision "shell", inline: "export DB_NAME=my_app_db"
  config.vm.provision "shell", inline: "export DB_USER=app_user" 
  config.vm.provision "shell", inline: "export DB_PASS=strongpassword" 

  # Database VM 
  config.vm.define "DB_VM" do |db|
    db.vm.box = "ubuntu/focal64" # Or "centos/7" 
    db.vm.hostname = "dbvm"
    db.vm.network "private_network", ip: "192.168.50.11" 

    # Database provisioning
    db.vm.provision "shell", path: "provision.sh"
  end

  # Application VM 
  config.vm.define "APP_VM" do |app|
    app.vm.box = "ubuntu/focal64"  # Or "centos/7" 
    app.vm.hostname = "appvm"
    app.vm.network "private_network", ip: "192.168.50.10"
    # or app.vm.network "forwarded_port", guest: 8080, host: 8080 

    # Application provisioning
    app.vm.provision "shell", path: "app_provision.sh" 
  end
end
